name: CI Required Reminder

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  reminder:
    name: Costly CI Check
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Please comment '/run-ci' to run CI."
          exit 1