name: Costly CI Check

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  costly-ci:
    name: Costly CI Check

    if: >
      github.event.issue.pull_request &&
      github.event.comment.body == '/run-ci'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head

      - name: Run costly CI
        run: echo "Running costly CI..."